# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Swordcode
tagline:          'Blog'
description:      'Bienvenidos al blog de <a href="http://swordcode.com" target="_blank">Swordcode</a>'

url:              http://swordcode.github.io
baseurl:          '/'
paginate:         5

author:
  name:           'Euclides Flores'
  url:            https://twitter.com/euclidesflores

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/swordcode/swordcode.github.io
